### ISSUE TITLE
pv-deletion fails, if lv does not exist anymore

### ISSUE THREAD

**Issue by mwennrich** [metal-stack/csi-lvm#52]
```
delete-pvc-0ca659b5-f472-4619-8ff7-c993d23fc800 csi-lvm-delete I0113 07:34:53.055746       1 main.go:40] starting csi-lvm-provisioner
delete-pvc-0ca659b5-f472-4619-8ff7-c993d23fc800 csi-lvm-delete I0113 07:34:53.055916       1 deletelv.go:61] delete lv pvc-0ca659b5-f472-4619-8ff7-c993d23fc800 vg:csi-lvm dir:/tmp/csi-lvm block:false
delete-pvc-0ca659b5-f472-4619-8ff7-c993d23fc800 csi-lvm-delete E0113 07:34:53.057827       1 deletelv.go:83] unable to umount /tmp/csi-lvm/pvc-0ca659b5-f472-4619-8ff7-c993d23fc800 from /dev/csi-lvm/pvc-0ca659b5-f472-4619-8ff7-c993d23fc800 output:umount: /tmp/csi-lvm/pvc-0ca659b5-f472-4619-8ff7-c993d23fc800: no mount point specified.
delete-pvc-0ca659b5-f472-4619-8ff7-c993d23fc800 csi-lvm-delete  err:%!w(*exec.ExitError=&{0xc00012e810 []})
delete-pvc-0ca659b5-f472-4619-8ff7-c993d23fc800 csi-lvm-delete E0113 07:34:53.057914       1 deletelv.go:87] unable to remove mount directory:/tmp/csi-lvm/pvc-0ca659b5-f472-4619-8ff7-c993d23fc800 err:%!w(*fs.PathError=&{remove /tmp/csi-lvm/pvc-0ca659b5-f472-4619-8ff7-c993d23fc800 2})
delete-pvc-0ca659b5-f472-4619-8ff7-c993d23fc800 csi-lvm-delete F0113 07:34:53.450816       1 deletelv.go:38] Error deleting lv: unable to delete lv: failed to list LVs: exit status 5 output:
delete-pvc-0ca659b5-f472-4619-8ff7-c993d23fc800 csi-lvm-delete goroutine 1 [running]:
delete-pvc-0ca659b5-f472-4619-8ff7-c993d23fc800 csi-lvm-delete k8s.io/klog/v2.stacks(0xc000136001, 0xc000214140, 0x80, 0x12f)
delete-pvc-0ca659b5-f472-4619-8ff7-c993d23fc800 csi-lvm-delete  /go/pkg/mod/k8s.io/klog/v2@v2.7.0/klog.go:1020 +0xb9

```

**Comment by Gerrit91** [comment]
This CSI will not be developed any further, please re-raise on csi-driver-lvm if necessary.
