### ISSUE TITLE
Pod create-pvc-x output log: "panic: Unrecognized command: createlv"

### ISSUE THREAD

**Issue by LoadingZhang** [metal-stack/csi-lvm#7]
Did I miss something?

**Comment by majst01** [comment]
Hi, 
any context would be helpful:
- full logs of the controller and the provisioner
- kubernetes version
- what physical disks are configured (controller.yaml)
- how does your pv(c) and pod manifest look like

**Comment by LoadingZhang** [comment]
sorry for late
k8s version: 1.16.2
controller logs:
```
I0210 00:58:32.458963       1 controller.go:1199] provision "elastic-cluster/elasticsearch-data-k8s-test-es-node-0" class "csi-lvm": started
I0210 00:58:32.462368       1 controller.go:86] start provision pvc-4deb473e-3bf4-41ea-9e1a-8adbd805c631 node:node1 devices:/dev/sd[b-z]
I0210 00:58:32.462383       1 controller.go:108] Creating volume pvc-4deb473e-3bf4-41ea-9e1a-8adbd805c631 at node1:/tmp/csi-lvm/pvc-4deb473e-3bf4-41ea-9e1a-8adbd805c631
I0210 00:58:32.462394       1 controller.go:234] start provisionerPod with args:[createlv --lvsize 1342177280000 --devices /dev/sd[b-z] --lvmtype mirror --lvname pvc-4deb473e-3bf4-41ea-9e1a-8adbd805c631 --vgname csi-lvm --directory /tmp/csi-lvm]
I0210 00:58:32.462459       1 event.go:274] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"elastic-cluster", Name:"elasticsearch-data-k8s-test-es-node-0", UID:"4deb473e-3bf4-41ea-9e1a-8adbd805c631", APIVersion:"v1", ResourceVersion:"29354729", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "elastic-cluster/elasticsearch-data-k8s-test-es-node-0"
I0210 00:58:32.469253       1 controller.go:346] provisioner pod status:Pending
I0210 00:58:51.516516       1 controller.go:346] provisioner pod status:Failed
E0210 00:58:52.521621       1 controller.go:135] error creating provisioner pod :create process timeout after 20 seconds
```
provisioner logs:
```
panic: Unrecognized command: createlv

goroutine 1 [running]:
main.cmdNotFound(0xc0002f6580, 0x7ffcab90cda0, 0x8)
	/work/cmd/controller/main.go:39 +0xad
github.com/urfave/cli.ShowCommandHelp(0xc0002f6580, 0x7ffcab90cda0, 0x8, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.2/help.go:213 +0x2c1
github.com/urfave/cli.glob..func1(0xc0002f6580, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.2/help.go:21 +0x50
github.com/urfave/cli.HandleAction(0x136aa40, 0x15f74f0, 0xc0002f6580, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.2/app.go:523 +0xbe
github.com/urfave/cli.(*App).Run(0xc00037c000, 0xc0000f6000, 0xe, 0xe, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.2/app.go:285 +0x5ec
main.main()
	/work/cmd/controller/main.go:184 +0x155
```

**Comment by majst01** [comment]
Hi,
can you please show me the output of:

```
k get pods -n csi-lvm -o yaml
```
and 

```
k get sc -o yaml
```

**Comment by LoadingZhang** [comment]
Of course. sc:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"csi-lvm"},"provisioner":"metal-pod.io/csi-lvm","reclaimPolicy":"Delete","volumeBindingMode":"WaitForFirstConsumer"}
  creationTimestamp: "2020-02-07T02:16:10Z"
  name: csi-lvm
  resourceVersion: "28093433"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/csi-lvm
  uid: f3a6be36-4d1e-4ad9-b5d2-876dfb343e7f
provisioner: metal-pod.io/csi-lvm
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
and pods info is here: https://del.dog/ogyllunita

**Comment by majst01** [comment]
Can you please recreate the controller with the most recent manifest from https://github.com/metal-stack/csi-lvm/blob/master/deploy/controller.yaml to ensure you have the correct image versions deployed.

**Comment by majst01** [comment]
We probably identified one possible reason for your problem: https://github.com/metal-stack/csi-lvm/commit/e09e88b785031de6ee99134c85946e01f9925e3a 
Can you please tell me what container runtime you are using ?

**Comment by majst01** [comment]
v0.4.1 contains https://github.com/metal-stack/csi-lvm/commit/e09e88b785031de6ee99134c85946e01f9925e3a

**Comment by LoadingZhang** [comment]
Sorry I mistake the image, i'm using controller image as provisioner image. https://del.dog/ogyllunita.txt#L40
And v0.4.1 works well, thanks

**Comment by majst01** [comment]
Thanks for reporting, closing.
